name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"

runs:
  using: "composite"
    steps: 
      - run: $GITHUB_ACTION_PATH/test.sh
        shell: bash

branding:
  icon: "mic"
  color: "purple"
