name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"

runs:
  using: "composite"
  steps:
    - run: chmod +x ${{ github.action_path }}/action.sh
      shell: bash
    - run: ${{ github.action_path }}/action.sh
      shell: bash

branding:
  icon: "mic"
  color: "purple"
