name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"

runs:
  using: "composite"
  steps:
    - run: chmod +x ${{ github.action_path }}/action.sh
      shell: bash
    - run: ${{ github.action_path }}/action.sh
      shell: bash
      working-directory: hello-github-actions

branding:
  icon: "mic"
  color: "purple"
