name: Notify development team via Slack
description: Utilize Buildbot Billy

inputs:
  BEARER:
    description: "A token for slack OAuth"
    required: true
  JOB:
    description: "the job we want to notify users about"
    required: true
  STATUS:
    description: "job status"
    default: ${{ inputs.JOB.status }}
  MESSAGE:
    description: "Message to send"
    default: "Hello world!"
  DEVELOPER:
    description: "developer that opened the pull request"
    default: ${{ github.event.pull_request.user.login }}
  CHANNEL:
    description: "Send the message to this channel"
    default: null

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.BEARER }}
    - ${{ inputs.JOB }}
    - ${{ inputs.MESSAGE }}
    - ${{ inputs.DEVELOPER }}
    - ${{ inputs.CHANNEL }}
