name: Notify development team via Slack
description: Utilize Buildbot Billy

inputs:
  BEARER:
    description: "A token for slack OAuth"
    required: true
  STATUS:
    description: "The job status"
    required: true
  MESSAGE:
    description: "Message to send"
    default: "Hello world!"
  DEVELOPER:
    description: "developer that opened the pull request"
    default: ${{ github.event.pull_request.user.login }}
  CHANNEL:
    description: "Send the message to this channel"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.BEARER }}
    - ${{ inputs.STATUS }}
    - ${{ inputs.MESSAGE }}
    - ${{ inputs.DEVELOPER }}
    - ${{ inputs.CHANNEL }}
