name: Notify development team via Slack
description: Utilize Buildbot Billy

inputs:
  BEARER:
    description: "A token for slack OAuth"
    required: true
  STATUS:
    description: "The job status"
    required: true
  MESSAGE:
    description: "Message to send"
    default: "Hello world!"
  DEVELOPER:
    descrption: "developer that pushed the commit"
    default: ${{  github.event.pusher.name }}

    DEVELOPER:
    descrption: "Send the message to this channel"
    default: "U0149HC3PFV"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.BEARER }}
    - ${{ inputs.STATUS }}
    - ${{ inputs.MESSAGE }}
    - ${{ inputs.DEVELOPER }}
