name: build
on:
  push:
    branches:
      - main
      # -

jobs:
  send-alert-to-channel-on-main-push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          username: "Gitbot"
          status: ${{ job.status }}
          fields: message,author,took
          author_name: Github Build ${{ job.status }}
          text: "Code has been merged to main"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if:
