name: build
on:
  push:
    branches:
      - main

jobs:
  send-to-channel:
    runs-on: ubuntu-latest
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          username: "Gitbot"
          status: ${{ job.status }}
          fields: message,author,took
          author_name: Github Build Notification
          text: "Code has been merged to main branch"
          channel: U8F99104R
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
