name: slack check suite notifications
description: Sends slack ping on check suite actions
on:
  workflow_dispatch:
  # watch:
  #   types: [check_run, check_suite]

jobs:
  send-notification-on-completion:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/checkout@v2
      - uses: ./buildbot-billy-action
        with:
          BEARER: ${{ secrets.BUILDBOT_BEARER }}
          MESSAGE: "hello world"
          JOB_NAME: "Testing action on check run"
