name: slack check suite notifications
description: Sends slack ping on check suite actions
on:
  check_run:
    types: [completed]

jobs:
  send-notification-on-completion:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/checkout@v2
      - uses: ./buildbot-billy-action
        with:
          BEARER: ${{ secrets.BUILDBOT_BEARER }}
          MESSAGE: ${{ fromJson(github.event.check_run.conclusion) }}
          JOB_NAME: "Testing action on check run"
