name: Send slack pings on branch merges.

on:
  push:
    branches:
      - main
      - staging

jobs:
  send-message-on-main-deploy:
    runs-on: ubuntu-latest
    if: ${{ always() && ${{ github.head_ref }} == 'main' }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./buildbot-billy-action
        with:
          BEARER: ${{ secrets.BUILDBOT_BEARER }}
          MESSAGE: "A deployment has been started to production"
          CHANNEL: "digiteam-deployments"
          HIDE_PR_DETAILS: true
  send-message-on-staging-deploy:
    runs-on: ubuntu-latest
    if: ${{ always() && ${{ github.head_ref }} == 'staging' }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./buildbot-billy-action
        with:
          BEARER: ${{ secrets.BUILDBOT_BEARER }}
          MESSAGE: "A deployment has been started to staging"
          CHANNEL: "digiteam-deployments"
          HIDE_PR_DETAILS: true
