name: A workflow for WATIR tests
on:
  workflow_dispatch:
#   schedule:
#     - cron: "0 6 * * *"
jobs:
  build:
    name: Runs WATIR Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./watir-action
        with:
          ENV: "Qa"
      - uses: ./watir-action
        with:
          ENV: "Staging"
      - uses: ./watir-action
        with:
          ENV: "Prod"
