name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test bash script
        run: |
          bash test.sh
      - uses: ./action-a
        with:
          MY_NAME: Brandy

          # ENV: QA
          # CI: true
          # RAILS_ENV: test
