name: A workflow for cron tests
on:
  schedule:
    - cron: "25 19 * * *"
jobs:
  build:
    name: Runs WATIR Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        # with:
        #   ref: "test-branch-checkout"
      - uses: ./watir-action
        with:
          ENV: "Qa"
      # - uses: actions/checkout@v1
      - uses: ./watir-action
        with:
          ENV: "Staging"
      - uses: ./watir-action
        with:
          ENV: "Prod"
