name: A workflow for my Hello World file
on:
  schedule:
    - cron: "0 6 * * *"
jobs:
  build:
    name: Runs WATIR Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./watir-action
