name: build
on: push
jobs:
  # job1:
  #   runs-on: ubuntu-latest
  #   # Map a step output to a job output
  #   outputs:
  #     users: ${{ steps.step1.outputs.test }}
  #     user: ${{ steps.step2.outputs.test }}
  #   steps:
  #   - id: step1
  #     run: echo "::set-output name=test::hello"
  #   - id: step2
  #     run: echo "::set-output name=test::world"
  # job2:
  #   runs-on: ubuntu-latest
  #   needs: job1
  #   steps:
  #   - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      users: ${{ steps.step1.outputs.users }}
      user: ${{ steps.step2.outputs.user }}
    steps:
      - id: step1
        run: echo ::set-output name=users::'{"begarland":"U8F99104R", "test":"12334"}'
      - id: step2
        run: echo ::set-output name=user::${{github.event.pusher.name}}
      - id: step3
        run: |
          content=`cat ./test.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=packageJson::$content"
  job3:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - id: test
        run: |
          echo ${{needs.job1.outputs.user}} ${{needs.job1.outputs.users}}
          echo ${{needs.job1.outputs.users.[needs.job1.outputs.user]}}

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Integration Test # default: 8398a7@action-slack
          fields: repo,commit,message,author # default: repo,commit
          channel: ${{needs.job1.outputs.users[needs.job1.outputs.user]}}
          if_mention: failure,cancelled, success
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled
