name: build
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      user: ${{ steps.step1.outputs.user }}
      users: ${{ steps.step2.outputs.users }}
    steps:
      - uses: actions/checkout@v1
      - id: step1
        run: echo ::set-output name=user::${{github.event.pusher.name}}
      - id: step2
        run: |
          content=`cat $GITHUB_WORKSPACE/users.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=users::$content"
  job3:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          username: "Gitbot"
          status: custom
          fields: ${{fromJson(needs.job1.outputs.users)[needs.job1.outputs.user].fields}}
          channel: ${{fromJson(needs.job1.outputs.users)[needs.job1.outputs.user].user_id}}
          author_name: Github Build Notification
          custom_payload: |
            {
              username: 'Gitbot',
              icon_emoji: ':party-wizard:',
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `${process.env.AS_JOB} ${{ job.status }} by ${process.env.AS_AUTHOR} has completed in ${process.env.AS_TOOK}`,
              }]
              channel: ${{fromJson(needs.job1.outputs.users)[needs.job1.outputs.user].user_id}}

            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: ${{fromJson(needs.job1.outputs.users)[needs.job1.outputs.user]}}
  job4:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          username: "Gitbot"
          status: ${{ job.status }}
          fields: repo,commit,message,author # default: repo,commit
          author_name: Github Build Notification

        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
