name: A workflow that should run soon
on: push
jobs:
  build:
    name: Runs a Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Bundle install
        run: |
          gem install bundler
          bundle config https://gems.weblinc.com
      - uses: actions/checkout@v1
      - uses: ./watir-action
        with:
          ENV: "Qa"
      - uses: actions/checkout@v1
        with:
          ref: "main"
      - uses: ./watir-action
        with:
          ENV: "Staging"
      - uses: actions/checkout@v1
        with:
          ref: "labeled-action"
      - uses: ./watir-action
        with:
          ENV: "Prod"
