name: A workflow that should run soon
on: push
jobs:
  build:
    name: Runs a Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./watir-action
        with:
          ENV: "Qa"
      - uses: actions/checkout@v2
        with:
          ref: "main"
      - uses: ./watir-action
        with:
          ENV: "Staging"
      - uses: actions/checkout@v2
        with:
          ref: "labeled-action"
      - uses: ./watir-action
        with:
          ENV: "Prod"
