name: A workflow that should run soon
on: push
jobs:
  QA:
    name: Runs the QA WATIR job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./watir-action
        with:
          ENV: "Qa"
      # - name: Clean up workspace
      #   run: |
      #     echo "Cleaning up previous run"
      #     sudo rm -rf "${{ github.workspace }}/testDir"
  STAGING:
    name: Runs the STAGING WATIR job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "main"
      - uses: ./watir-action
        with:
          ENV: "Staging"
      # - name: Clean up workspace
      #   run: |
      #     echo "Cleaning up previous run"
      #     sudo rm -rf "${{ github.workspace }}/testDir"
  PROD:
    name: Runs the Production WATIR job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "labeled-action"
      - uses: ./watir-action
        with:
          ENV: "Prod"
      # - name: Clean up workspace
      #   run: |
      #     echo "Cleaning up previous run"
      #     sudo rm -rf "${{ github.workspace }}/testDir"
