name: A workflow for WATIR tests
on:
  schedule:
    - cron: "30 19 * * *"
jobs:
  build:
    name: Runs WATIR Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: "test-checkout-branch"
      - uses: ./watir-action
        with:
          ENV: "Qa"
      - uses: actions/checkout@v1
        with:
          ref: "main"
      - uses: ./watir-action
        with:
          ENV: "Staging"
      - uses: ./watir-action
        with:
          ENV: "Prod"
