name: Send channel and developer notifications
on:
  push:
    branches:
      - "*"
      - "!main"
  pull_request:
    types: [opened, closed]
  pull_request_review:
    types: [submitted, edited, dismissed]

jobs:
  get-dev:
    runs-on: ubuntu-latest
    outputs:
      user: ${{ steps.step1.outputs.user }}
      users: ${{ steps.step2.outputs.users }}
    steps:
      - uses: actions/checkout@v1
      - id: step1
        run: echo ::set-output name=user::${{github.event.pusher.name}}
      - id: step2
        run: |
          content=`cat $GITHUB_WORKSPACE/users.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=users::$content"
  send-to-dev:
    runs-on: ubuntu-latest
    needs: get-dev
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          username: "Gitbot"
          status: ${{ job.status }}
          fields: ${{fromJson(needs.get-dev.outputs.users)[needs.get-dev.outputs.user].fields}}
          channel: ${{fromJson(needs.get-dev.outputs.users)[needs.get-dev.outputs.user].slack_id}}
          author_name: Github Build Notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: ${{fromJson(needs.get-dev.outputs.users)[needs.get-dev.outputs.user].notify_via_dm}}
  send-to-channel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./slack-action
        # with:
        #   username: "Gitbot"
        #   status: ${{ job.status }}
        #   # fields: author,took # default: repo,commit
        #   author_name: Github Build ${{ job.status }}
        #   text:
        # env:
        #   SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        # if: always()
