name: Billy sends channel and developer notifications
on: pull_request

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.step1.outputs.status }}
      jobName: ${{ steps.step2.outputs.jobName }}
    steps:
      - id: step1
        run: echo "::set-output name=status::${{ job.status }}"
      - id: step2
        run: echo "::set-output name=jobName::${{ github.job }}"

  send-message:
    runs-on: ubuntu-latest
    if: always()
    needs: job1
    steps:
      - uses: actions/checkout@v2
      - uses: ./buildbot-billy-action
        with:
          BEARER: ${{ secrets.BUILDBOT_BEARER }}
          STATUS: ${{ needs.job1.outputs.status }}
          JOB_NAME: ${{ needs.job1.outputs.jobName }}
  # send-another-message:
  #   needs: get-dev
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: ./buildbot-billy-action
  #       with:
  #         BEARER: ${{ secrets.BUILDBOT_BEARER}}
  #         MESSAGE: ":party-parrot:"
