name: Billy sends channel and developer notifications
on: push

jobs:
  send-message:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/checkout@v2
      - uses: ./buildbot-billy-action
        with:
          BEARER: ${{ secrets.BUILDBOT_BEARER}}
          STATUS: "${{ job.status }} "
          MESSAGE: "${{ job.status }} "
          CHANNEL: "treehouse"
  # send-another-message:
  #   needs: get-dev
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: ./buildbot-billy-action
  #       with:
  #         BEARER: ${{ secrets.BUILDBOT_BEARER}}
  #         MESSAGE: ":party-parrot:"
