name: Billy sends channel and developer notifications
on: pull_request

jobs:
 status:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.step1.outputs.status }}
    steps:
      - uses: actions/checkout@v1
      - id: step1
        run: echo ::set-output name=status::${{ job.status }}
  send-message:
    runs-on: ubuntu-latest
    if: always()
    needs: status
    steps:
      - uses: actions/checkout@v2
      - uses: ./buildbot-billy-action
        with:
          BEARER: ${{ secrets.BUILDBOT_BEARER}}
          STATUS: "${{ needs.status.outputs.status }} "
          MESSAGE: ":party-wizard:"
  # send-another-message:
  #   needs: get-dev
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: ./buildbot-billy-action
  #       with:
  #         BEARER: ${{ secrets.BUILDBOT_BEARER}}
  #         MESSAGE: ":party-parrot:"
