name: Billy sends channel and developer notifications
on: push

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./buildbot-billy-action
        with:
          BEARER: ${{ secrets.BUILDBOT_BEARER}}
          CHANNEL: ${{fromJson(needs.get-dev.outputs.users)[needs.get-dev.outputs.user].slack_id}}
          MESSAGE: "Your job ${{fromJson(needs.get-dev.outputs.messages).job.status[job.status]}}"
  # send-another-message:
  #   needs: get-dev
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: ./buildbot-billy-action
  #       with:
  #         BEARER: ${{ secrets.BUILDBOT_BEARER}}
  #         MESSAGE: ":party-parrot:"
