name: Billy sends channel and developer notifications
on: push

jobs:
  send-message:
    - uses: actions/checkout@v2
    - uses: ./buildbot-billy-action
      with:
        BEARER: ${{ secrets.BUILDBOT_BEARER }}
