name: Billy sends channel and developer notifications
on: pull_request

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      job: ${{ steps.step1.outputs.job }} # map step output to job output
    steps:
      - id: step1
        name: save job value
        run: echo "::set-output name=job::${{job}}"
  send-message:
    runs-on: ubuntu-latest
    if: always()
    needs: job1
    steps:
      - uses: actions/checkout@v2
      - uses: ./buildbot-billy-action
        with:
          BEARER: ${{ secrets.BUILDBOT_BEARER}}
          STATUS: ${{ needs.job1.outputs.job.status }}
          MESSAGE: ":party-wizard: ${{needs.job1.outputs.job}}"
  # send-another-message:
  #   needs: get-dev
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: ./buildbot-billy-action
  #       with:
  #         BEARER: ${{ secrets.BUILDBOT_BEARER}}
  #         MESSAGE: ":party-parrot:"
